### PR TITLE
Py3

### PR DESCRIPTION
**Pull request by zshaheen**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@zshaheen I'm not sure you setup your test suite to ran both against py3 and py2 seems like you're only testing in against python2

**Comment by zshaheen** [comment]
@doutriaux1 Ahh, good idea. I tested it on Python 3 locally, not with Travis/circleCI. I'll do that.

**Comment by doutriaux1** [comment]
@zshaheen looked at any of our .travis files we test both py2 and py3

**Comment by zshaheen** [comment]
Haha, that's exactly what I'm doing.

**Comment by doutriaux1** [comment]
@zshaheen don't forget to upload both python to anaconda as well

**Comment by doutriaux1** [comment]
thx!

**Pull request merged**
