### PR TITLE
Viewer

### PR DESCRIPTION
**Pull request by zshaheen**
* Removed driver class because it doesn't need to be a class
* viewer added
* incomplete example added, will finish when I got time

### CODE REVIEW

**Comment by chaosphere2112** [comment]
:clap:

**Comment by durack1** [comment]
@zshaheen this looks interesting, I'd be interested to get a heads up about this when you have a moment

**Comment by zshaheen** [comment]
@durack1 I have a demo with the viewer here: https://github.com/UV-CDAT/cdp/blob/master/example/basic_driver.py

You can clone this repo and it should work. You do need @chaosphere2112 's output viewer, it's a dependency. Grab it like this:

`conda install output_viewer -c conda-forge -c uvcdat`

Hopefully this week, I'll add a Jupyter notebook so the pmp guys can use this. Stop by my office whenever.

**Comment by doutriaux1** [comment]
@zshaheen we need to 
1- Add this dependency to meta.yaml (if not done yet)
2- Make sure it only fails when it needs it not right away.

**Comment by zshaheen** [comment]
@doutriaux1 It's a dependency, but I didn't upload this stuff to anaconda (with the new meta.yml). So until I do that, you got to install the output_viewer separately. Will do that this week.

**Pull request merged**
