### PR TITLE
Added caching

### PR DESCRIPTION
**Pull request by zshaheen**
This is just basic caching, should probably add an lru cache and support for python3's lru_cache.

### CODE REVIEW

**Comment by durack1** [comment]
@zshaheen this sounds like a nice optimization, but what does it actually achieve? Got any web links to point out here?

**Comment by zshaheen** [comment]
@durack1 all this does is save the results of a metrics calculation in a dictionary, so if the same metric doesn't need to be recalculated. The function name and args are the key of the dictionary.

**Comment by durack1** [comment]
@zshaheen so memory objects or file objects? As we start ramping up things in the PMP I can imagine that these objects could start to get VERY numerous..

@gleckler1 @doutriaux1 pinging you both here

**Comment by doutriaux1** [comment]
@durack1 memory, the idea is to store/cache results to speed up computation, e.g if many metrics use `standard deviation` no need to compute it everytime. @zshaheen there's a flag to store/clear cache right?

**Comment by zshaheen** [comment]
@durack1 @doutriaux1 Yes, there a way for the user to clear the cache. Implementing an LRU cache would limit the size and address any potential memory issues. This isn't an lru cache btw, but I plan on implementing one eventually.

**Pull request merged**
